export default function handler(req, res) {
    res.status(200).json(`To use the university endpoint, use the following format: /api/university/[university]/programs. For example, /api/university/university-of-toronto/programs. The university name must be one of the following:

university-of-toronto,
university-of-british-columbia,
mcgill-university,
mcmaster-university,
university-of-alberta,
university-of-montreal,
university-of-calgary,
university-of-ottawa,
university-of-waterloo,
university-of-western-ontario,
simon-fraser-university,
dalhousie-university,
university-of-victoria,
laval-university,
university-of-manitoba,
queens-university,
york-university,
carleton-university,
university-of-guelph,
university-of-saskatchewan,
concordia-university,
memorial-university-of-newfoundland,
université-de-québec-à-montréal,
university-of-sherbrooke,
toronto-metropolitan-university,
university-of-new-brunswick,
university-of-regina,
university-of-ontario-institute-of-technology,
university-of-windsor,
wilfrid-laurier-university,
lakehead-university,
brock-university,
laurentian-university,
trent-university`)
}